plant_simulation:
  prog_id: "Tecnomatix.PlantSimulation.RemoteControl"
  template_path: "C:/Users/gpgs16/Documents/adk_agents/auto_sim/data/Simulation_Model_Template/ASMG_model_template.spp"
  dest_dir: "C:/Users/gpgs16/Documents/adk_agents/auto_sim/data/Simulation_Model_Output"
  object_templates:
    source: "Source"
    drain: "Drain"
    station: "Station"
    conveyor: "Conveyor"
    buffer: "Buffer"
    turntable: "TurnTable"
  object_paths:
    model_frame: ".Models.Model"
    connector: ".MaterialFlow.Connector"
    user_object: ".UserObjects.{template_name}"

cmsd_xml:
  output_dir: "C:/Users/gpgs16/Documents/adk_agents/auto_sim/data/CMSD_XML_Output"
  file_prefix: "cmsd_xml_"
  file_extension: ".xml"

simtalk:
  python_dll_path: "C:/Users/gpgs16/anaconda3/envs/auto_sim/python312.dll"
  interpreter_path: "C:/Users/gpgs16/Documents/adk_agents/auto_sim/interpreter/interpreter.py"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
